# 第十二章实验

## 12-1

编写程序12-1.cpp，在Cexception类的成员函数Reason()中用cout显示异常的类型，在函数fn1()中通throw语句触发异常，在主函数的try模块中调用fn1()，在catch模块中捕获异常。
